version: '3.8'
services:
  server:
    build:
      dockerfile: docker/Dockerfile.server
    image: server_image
    container_name: server_container
    networks:
      - internal
    env_file:
      - .env
    expose:
      - "8000"
    ports:
      - "8000:8000"
    command: bash -c "poetry run uvicorn main:app --host 0.0.0.0 --port 8000"

networks:
  internal:
    driver: bridge