version: '3.8'
services:
  tests:
    build:
      context: ../
      dockerfile: docker/Dockerfile.gateway
    image: test_image
    container_name: test_container
    networks:
      - internal
    env_file:
      - ../.env
    volumes:
      - .:/app
    expose:
      - "8000"
    ports:
      - "8000:8000"
    command: bash -c "poetry run uvicorn main:app --host 0.0.0.0 --port 8000"

networks:
  internal:
    driver: bridge